load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("@rules_cc//cc:cc_test.bzl", "cc_test")

cc_library(
    name = "object_pool",
    hdrs = ["object_pool.h"],
)

cc_test(
    name = "object_pool_test",
    srcs = ["object_pool_test.cpp"],
    copts = ["-std=c++23"],
    deps = [
        ":object_pool",
        "@catch2//:catch2_main",
    ],
)

cc_test(
    name = "object_pool_test_asan_ubsan",
    srcs = ["object_pool_test.cpp"],
    copts = [
        "-std=c++23",
        "-fsanitize=address,undefined",
        "-fno-omit-frame-pointer",
    ],
    linkopts = ["-fsanitize=address,undefined"],
    deps = [
        ":object_pool",
        "@catch2//:catch2_main",
    ],
)
